In [ ]:
#1Sayılardan oluşan bir boyutlu array oluşturulur. 
#Arrayi oluştururken sayıların veri tipini integer olarak belirtilir.
#Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakılır.

In [107]:
import numpy as np
arr=np.array([1, 2, 3, 4, 5,6,7,8,9,10], dtype=int)

In [108]:
print(arr.ndim)

1


In [109]:
print(arr.size)

10


In [ ]:
#2İki ve üç boyutlu arrayler oluşturulur. 
#Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşılır.
#Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır.

In [48]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr3=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])

In [49]:
print(arr2.ndim) 
print(arr3.ndim)

2
3


In [50]:
print(arr2.size)
print(arr3.size)

10
12


In [51]:
np.shape(arr2)

(2, 5)

In [52]:
np.shape(arr3)

(1, 4, 3)

In [53]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [54]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [55]:
#arr2 de 1. satır 4. elemana ulaşalım.
arr2[1,-1] or arr2[1,4]

10

In [56]:
#arr3 de 2. satır 1. elemana ulaşalım.
arr3[0,2,1]

8

In [57]:
#5,10 sayıslarını seçelim.
arr2[:,-1]

array([ 5, 10])

In [67]:
#2,3,4,7,8,9 sayılarını seçelim.
arr2[::,1:4]

array([[2, 3, 4],
       [7, 8, 9]])

In [69]:
#8,9,11,12 sayılarını seçelim.
arr3[0,2:,1:]

array([[ 8,  9],
       [11, 12]])

In [70]:
#1,4,7 sayılarını seçelim.
arr3[0,0:3,0]

array([1, 4, 7])

In [ ]:
#3Numpy fonksiyonu kullanarak bir, iki ve üç boyutlu arrayler oluşturulur. 
#Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır

In [84]:
import numpy as np

In [87]:
arr4=np.array([8,7,6,5,4])
arr5=np.array([[5,12,14,17,20],[3,7,9,11,13]])
arr6=np.array([[[2,4,6,8,16]],[[98,96,94,92,90]]])

In [99]:
arr4[4]

4

In [95]:
arr5[1,4]

13

In [97]:
arr6[0,0,2]

6

In [100]:
arr4[::]

array([8, 7, 6, 5, 4])

In [104]:
arr5[:,3:]

array([[17, 20],
       [11, 13]])

In [106]:
arr6[:,0:,1:4]

array([[[ 4,  6,  8]],

       [[96, 94, 92]]])

In [ ]:
#4Sıfırlardan oluşan ve birlerden oluşan iki tane iki boyutlu array oluşturulur.
#Bu arrayler satır ve sütun bazında birleştirilir.

In [118]:
arr1=np.array([1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],ndmin=2)
print(arr1)

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]


In [119]:
arr0=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,],ndmin=2)
print(arr0)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [120]:
np.concatenate([arr1,arr0])

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [123]:
np.concatenate([arr1,arr0],axis=1)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])